### ISSUE TITLE
Propertys Name in listproyects and ListHubs Undefined

### ISSUE THREAD

**Issue by phrakendark** [petrbroz/forge-server-utils#19]
https://github.com/petrbroz/forge-server-utils/blob/22d8d7e36d29d1525846c6eb6a255d26991e5568/src/bim360.ts#L357

Route hubs https://developer.api.autodesk.com/project/v1/hubs
before "data.name"  after  "result.data.attributes.name" new property location

Route https://developer.api.autodesk.com/project/v1/hubs/:hubid/projects

before "data.name"  after  "result.data.attributes.name" new property location

**Comment by petrbroz** [comment]
Thank you. The issue is fixed and will be available with the next release.
