### ISSUE TITLE
uploadObject function - Uploading file larger than 10MB

### ISSUE THREAD

**Issue by lgib1669** [petrbroz/forge-server-utils#26]
I have an issue with the uploadObject fonction from forge-server-utils. I receive Request body larger than maxBodyLength limit error on the request.
The problem is coming on file larger than 10MB (you can find the sample in the attachments).
[sample_bodyLengthError.zip](https://github.com/petrbroz/forge-server-utils/files/6102910/sample_bodyLengthError.zip)

What is strange is that I cannot replicate the error using forge-apis module. However, implementing my "own" axios request in setting maxBodyLength and maxContentLength to Infinity will lead to the same error.

**Comment by petrbroz** [comment]
Thank you for the heads up! I believe this is an issue specific to `axios`. The `forge-apis` library is using `request` (https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/package.json#L31).

I'm setting maxContentLength to infinity as well (https://github.com/petrbroz/forge-server-utils/blob/develop/src/common.ts#L6) but I read somewhere that this may not be working. Let me investigate that.
