### ISSUE TITLE
Question : is this the next step of forge-server-utils

### ISSUE THREAD

**Issue by lijiayi0921** [petrbroz/forge-server-utils#50]
Hi,
I'm using forge-server-utils for 3 years and it seems to no longer being maintained (we detected failed forge-server-utils since this week, and started to move from it).
However just discovered this package.
Is it the next step of  forge-server-utils + other features, combined into one package ?
Thank you
Jiayi

**Comment by petrbroz** [comment]
Hi @lijiayi0921, yes, this repo was originally called forge-server-utils, and it's been later renamed to aps-sdk-node.

Please note that this is an unofficial/experimental project. We now have a dedicated team that builds official SDKs (https://aps.autodesk.com/blog/migrating-new-aps-nodejs-sdk-0) so I'd definitely suggest using those moving forward.
